services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    expose: 
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
  api-ts:
    container_name: api-ts
    build: 
      context: ./api-ts
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    environment:
      - POSTGRES_URL=postgresql://postgres:1234@postgres:5432/postgres
    volumes:
      - /app/node_modules
      - ./api-ts:/app
  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile.dev
    expose:
      - 5173
    volumes:
      - /app/node_modules
      - ./web:/app
    environment:
      - WDS_SOCKET_PORT=0
