services:
  nginx:
    container_name: nginx
    image: kwangdock/portfolio-tech-stack-nginx
    restart: always
    depends_on:
      - web
      - api-ts
      - api-java
      - api-python
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf/:/etc/nginx/ssl
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf/:/etc/letsencrypt
  api-ts:
    container_name: api-ts
    image: kwangdock/portfolio-tech-stack-api-ts
    expose:
      - 5000
    env_file:
      - .env
  api-java:
    container_name: api-java
    image: kwangdock/portfolio-tech-stack-api-java
    expose:
      - 5000
    env_file:
      - .env
  api-python:
    container_name: api-python
    image: kwangdock/portfolio-tech-stack-api-python
    expose:
      - 5000
    env_file:
      - .env
  web:
    container_name: web
    image: kwangdock/portfolio-tech-stack-web
    expose:
      - 3000
