services:
  nginx:
    container_name: nginx
    restart: always
    depends_on:
      - web
      - api
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    expose: 
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
  redis:
    container_name: redis
    image: redis:7
    restart: always
    expose:
      - 6379
  api:
    container_name: api
    depends_on:
      - postgres
      - redis
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
    expose:
      - 5000
    environment:
      - REDIS_URL=redis://redis
      - PSQL_URL=postgresql://postgres:1234@postgres:5432/postgres
  worker:
    container_name: worker
    depends_on:
      - redis
    build: 
      context: ./worker
      dockerfile: Dockerfile.prod
    environment:
      - REDIS_URL=redis://redis
  web:
    container_name: web
    build: 
      context: ./web
      dockerfile: Dockerfile.prod
    expose:
      - 3000
