services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    expose: 
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
  api-ts:
    container_name: api-ts
    build: 
      context: ./api-ts
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    environment:
      - POSTGRES_URL=postgresql://postgres:1234@postgres:5432/postgres
    volumes:
      - /app/node_modules
      - ./api-ts:/app
  api-java:
    container_name: api-java
    build: 
      context: ./api-java
      dockerfile: Dockerfile.dev
    expose:
      - 8080
    environment:
      - DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=1234
  web:
    container_name: web
    image: kwangdock/portfolio-tech-stack-web
    expose:
      - 3000

