services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 3000:80
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    expose: 
      - 5432
    env_file:
      - .env.dev
  api-ts:
    container_name: api-ts
    build: 
      context: ./api-ts
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    env_file:
      - .env.dev
    volumes:
      - /app/node_modules
      - ./api-ts:/app
  api-java:
    container_name: api-java
    build: 
      context: ./api-java
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    env_file:
      - .env.dev
  api-python:
    container_name: api-python
    build: 
      context: ./api-python
      dockerfile: Dockerfile.dev
    expose:
      - 8000
    env_file:
      - .env.dev
    volumes:
      - ./api-python:/app
  web:
    container_name: web
    image: kwangdock/portfolio-tech-stack-web
    expose:
      - 3000
